# Generated by Django 4.1.5 on 2023-01-07 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="subtitle",
            new_name="subtitulo",
        ),
        migrations.AlterField(
            model_name="post",
            name="data_publicacao",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 7, 16, 52, 24, 149987)
            ),
        ),
    ]
