# Generated by Django 4.1.5 on 2023-01-06 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="data_publicacao",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 6, 15, 46, 28, 57440)
            ),
        ),
    ]
