# Generated by Django 4.1.5 on 2023-01-07 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_subtitle_post_subtitulo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="data_publicacao",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 7, 16, 56, 7, 683222)
            ),
        ),
    ]
