# Generated by Django 4.1.5 on 2023-01-07 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_data_publicacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="data_publicacao",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 7, 20, 11, 16, 857636, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
