# Generated by Django 4.1.5 on 2023-01-09 22:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_data_publicacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="conteudo",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
